language: node_js
node_js:
  - '14.15.5'

install:
  - npm install newman

before script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run tests/Frontend_Calls.postman_collection.json -e tests/aliyun_staging.postman_environment.json --reporters html --reporter-html-export C:\postman\collection\Report\APITestResult_%date%.html